name: Node.js CI

on:
  workflow_call:
  pull_request:
  push:
    branches:
      - unstable

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v2
    - uses: oven-sh/setup-bun@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: bun install
    - name: Lint
      run: bun lint
    - name: Tests
      run: bun test:jest
    